### PR TITLE
Added CONSOLE envvar to control console output

### PR DESCRIPTION
**Pull request by kstrauser**
By default, CONSOLE is true. When set to false, start-minecraft.sh
adds "--noconsole" to java. Use this to keep Spigot from burning CPU.

### CODE REVIEW

**Comment by kstrauser** [comment]
CI seems to be wonky. I'll revisit this tonight.

**Comment by itzg** [comment]
I'll look later too since I bet its one of the other images (usually Cassandra) that's simply failing due to an old download.

**Comment by kstrauser** [comment]
Cool. I'd forgotten to update both branches of the with/without bootstrap code anyway.

**Comment by itzg** [comment]
OK, if you `git pull` from master branch of https://github.com/itzg/dockerfiles then I have pushed the Cassandra fix that's failing the build. With that you can re-push and the build should go green.

If that becomes a hassle, then I'm cool with merging as it is since the changes look totally fine to me.

**Comment by itzg** [comment]
FYI, here's the clean build of master:

https://circleci.com/gh/itzg/dockerfiles/167

**Comment by kstrauser** [comment]
I've rebased off your master and force pushed. Crossing my fingers...

**Comment by kstrauser** [comment]
\o/

**Pull request merged**
