### PR TITLE
minecraft-server: Fixed FORGEVERSION case, add support for BIOMESOP

### PR DESCRIPTION
**Pull request by dirkcjelli**
First of all: Thanks for your minecraft-server image, I really like it 👍 

* Fixed FORGEVERSION in case statement to working FORGE_VERSION
   * Removed default case because `FORGE_VERSION=$FORGE_VERSION` doesn't make a lot of sense if nothing needs to be changed.
* Add support for BIOMESOP level-type

### CODE REVIEW

**Comment by itzg** [comment]
Thanks! That `FORGEVERSION` has been bugging me lately since I've been in and around that code. The only challenge in changing that is that [the docs](https://github.com/itzg/dockerfiles/blob/master/minecraft-server/README.md#running-a-forge-server) reference `FORGEVERSION`. As a migration, can you make a few more changes:

1. Update the README to reference `FORGE_VERSION`
2. Update the default env var name [here](https://github.com/itzg/dockerfiles/blob/master/minecraft-server/Dockerfile#L48)
3. Above the case block, for anyone using the old variable, put a `if [[ -n $FORGEVERSION ]]; then FORGE_VERSION=$FORGEVERSION; fi` for backfilling old into current

**Comment by itzg** [comment]
I just noticed that this will fix #139 , so if you don't mind I'm going to revert just the `FORGEVERSION` change. That way I can at least merge part of your change for now.

**Comment by dirkcjelli** [comment]
Hi,

sorry for the delay, I'll be able to have a look at this today evening. :)

**Comment by itzg** [comment]
I totally understand. Since I went ahead and merged the level type change, I hope you don't mind opening a new PR for the remainder. Thanks.

**Pull request merged**
