### PR TITLE
Added the ability to select forge version

### PR DESCRIPTION
**Pull request by 55chevypickup**
Added the ability to select forge version by adding -e FORGEVERSION=10.13.3.1403-1.7.10 or -e FORGEVERSION=RECOMMENDED

### CODE REVIEW

**Comment by itzg** [comment]
Great addition. I'll give it a sanity test this evening, but the code change looks good. 

Don't worry about the failed build -- it's an out of date Cassandra container that I fixed on the master branch. If you want to merge latest from `itzg:master`, that'll clear that up.

**Comment by itzg** [comment]
Wow, their file naming gets inconsistent within the 1.7.10's. For the current recommended, the file name is `forge-1.7.10-10.13.2.1291-universal.jar` but for the versions at or just below latest it's `forge-1.7.10-10.13.3.1408-1.7.10-universal.jar` (leading and trailing "1.7.10").

Might have to come up with some smarts in the script to simplify that for users, but let's get your changes out there.

Thanks for the contribution.

**Comment by itzg** [comment]
Built and pushed with image ID 7042f7009e90

**Comment by 55chevypickup** [comment]
Thanks. I noticed the version numbering too but wasn't quite sure how to handle it.

**Pull request merged**
