### PR TITLE
Whitelist players

### PR DESCRIPTION
**Pull request by everett-toews**
Interested in easy whitelisting for your Minecraft image?

### CODE REVIEW

**Comment by itzg** [comment]
Great addition. Thanks!

**Comment by itzg** [comment]
The property is `white-list` (with a dash) in the current version at least. So I covered all the bases with one more change in 32cb5f44e43822f6c4e160f31c8cb250ec61638f

**Comment by everett-toews** [comment]
Thanks for the snappy review and merge. Looks like there was an error with the [latest build](https://hub.docker.com/r/itzg/minecraft-server/builds/) and the build logs are unrecoverable. I assume it's just Docker Hub acting up. Rebuild?

**Comment by itzg** [comment]
Yep, now [it went through](https://hub.docker.com/r/itzg/minecraft-server/builds/bjbiahv2aquvjgtgurkcxdf/)

**Pull request merged**
