### PR TITLE
propagate SIGTERM to the Minecraft process

### PR DESCRIPTION
**Pull request by andreasheil**
using exec to properly shutdown the Minecraft process

### CODE REVIEW

**Comment by itzg** [comment]
I have been using bash for years and didn't know that about the `exec` builtin. Thanks!

**Comment by itzg** [comment]
Kicked off [a build](https://registry.hub.docker.com/u/itzg/minecraft-server/build_id/5652/code/bpdzgdg8pegwnhedhzezjed/)

**Comment by itzg** [comment]
Image ID is cc87cf4cc24a

**Comment by andreasheil** [comment]
You're welcome!

**Pull request merged**
