### PR TITLE
Add difficulty knob.

### PR DESCRIPTION
**Pull request by timvisher**
Allows setting difficulty level for the server via an environment variable.

### CODE REVIEW

**Comment by itzg** [comment]
Oh yeah, that's a great knob to have. Thanks.

Do you mind also adding a little snippet in README?

**Comment by timvisher** [comment]
There you go. :)

**Comment by itzg** [comment]
Sorry, I hadn't noticed before -- how about a default of `normal` or `easy`? It looks like the stock default is easy, which I think is the same for the client.

**Comment by itzg** [comment]
Sorry for the delay on merging. It's built and pushed to Docker hub -- image ID 2bca89e353c5.

**Pull request merged**
