### PR TITLE
Add ability to change online-mode from environment variable when contained created

### PR DESCRIPTION
**Pull request by jimtremblay**

### CODE REVIEW

**Comment by itzg** [comment]
Thanks for the contribution. Can I ask for two more little changes?

- Add a section under [Server Configuration](https://github.com/itzg/dockerfiles/tree/master/minecraft-server#server-configuration) for the new option
- Add a default value of `ONLINE_MODE` to the [ENV here](https://github.com/itzg/dockerfiles/blob/master/minecraft-server/Dockerfile#L38)

**Comment by jimtremblay** [comment]
Here it is! I appreciate your feedback.

If you have more suggestions, let me know.

Thanks,
Jim

**Comment by itzg** [comment]
Pushed to hub at `sha256:6827b849a4a88a6a20a9d0f1dc04ff137686d48df3ce005048705aa445a16fc0`

**Comment by jimtremblay** [comment]
Thanks!

**Pull request merged**
